### ISSUE TITLE
Batch 4?

### ISSUE THREAD

**Issue by ellytsa** [LetsUpgrade/Free-Coding-School-Python#1]
Unfortunately, I have been unable to keep up and I have missed a couple days..I would like to start over if there will be a batch 4 following this one. Could I sign up for it?

**Comment by Hardik048** [comment]
The admins will post about any further updates.

**Comment by ellytsa** [comment]
thank you, I'll keep checking.

**Comment by ellytsa** [comment]
Good evening,
This morning's class was very difficult to follow. The video kept freezing
and the remaining 15-20 minutes I had no connection at all.
Unfortunately, I misunderstood as to where we had to do the assignment and
I did mine in Jupyter. But I can not upload it into the assignment platform
now, because I noticed that the assignments had to be done in Google colab.
It is very late however now and I will have to take time to learn how to
use colab and then do all my assignment over again.
Could I somehow just send my notebook?
Thanks,
Elli
[image: photo]
*Elli Mihalopoulou*

*Event Coordinator*Freelance Writer/Virtual Assistance
p:+30 2273033524| m:694 644 6055 | e:ellimihalopoulou@gmail.com
<elli.mihalopoulou@gmail.com>
<http://facebook.com/elli.mihalopoulou> [image:
gr.linkedin.com/in/ellimihalopoulou]
<http://gr.linkedin.com/in/ellimihalopoulou>
<http://twitter.com/%3Cellytsa%3E>
<http://plus.google.com/u0+EllytsaMihalopoulouposts>
<http://blogger.com/profile/%3Cthekarlovasicrafter%3E>
