### ISSUE TITLE
DOUBT 

### ISSUE THREAD

**Issue by sirilalithaadapa** [LetsUpgrade/Free-Coding-School-Python#22]
I have been submitting my assignments from 2 days but ... Actually i have a doubt regarding it we need too submit all my  assignments then participants will get a certificate or else if we submit one assignments we will  get can u just explain it ... COZ i am just new to this ****

**Comment by rajatpandey95** [comment]
You have to submit all

**Comment by sirilalithaadapa** [comment]
okay thank u!
